### PR TITLE
create a library folder in submitty

### LINKED ISSUE #28: [library] Create a library folder in submitty
**What problem are you trying to solve with Submitty**
Update the install process to create a folder for the library. The submitty user should have full control of this folder. 

**Describe the way you'd like to solve this problem**
The process may only be updates to the install documentation. Only if it can not be automated.

### PR DESCRIPTION
**Pull request by dakriy**
Create a default library folder. Still need to make tests for it.
Closes #28

### CODE REVIEW

**Comment by sballance** [comment]
@dakriy this looks good to me. Just needs tests.

**Comment by dakriy** [comment]
So like. This is done and the folder is there and whatnot, I just still need to write tests for it. Feel free to merge it into your own branch if you need it.

**Comment by stephenermshar** [comment]
Travis build was failing because of `WIP` in name, removed `[WIP]` from title.

**Comment by 3dCameron** [comment]
After the WIP fix, this appears to be good. We'll merge this once the tests finish (assuming they pass).

**Comment by dakriy** [comment]
I mean. Thanks guys, but I had the WIP there because I still need to write tests for it. lol Whatever I can write tests in another issue I guess.

**Pull request merged**
