### PR TITLE
ElectronicGrader query relocation

### PR DESCRIPTION
**Pull request by N-Perry**
### Please check if the PR fulfills these requirements:

* [ ] The PR title and message follows our [guidelines](https://submitty.org/developer/how_to_contribute)
* [ ] Tests for the changes have been added/updated (if possible)
* [ ] Documentation has been updated/added if relevant

### Other information?

This assignment was worked on by NICK MORIN, CAMERON BIERWAGON, and NICK PERRY

### CODE REVIEW

**Comment by N-Perry** [comment]
woops i forgot i should be requesting to merge with the issue#4537 branch

**Comment by N-Perry** [comment]
> woops i forgot i should be requesting to merge with the issue#4537 branch

okay i think i fixed it, should be requesting to merge into the right branch now

**Comment by mwilde1998** [comment]
As far as I can tell, it looks good; I don't see any getQueries in the view. 
Disclaimer: I don't know crap about php.

**Comment by dakriy** [comment]
Why let this merge when the tests/build doesn't pass? :( Now we have broken code. :(

**Pull request merged**
